# config.yaml
model: GINNet
type: 0
data_dir: data/ModelNet40
output: output/Gabriel_Modelnet40
epochs: 300
batch: 256
lr: 0.001
min_lr: 0.0000001
dropout: 0.5
keys: pos
graph_type: gabriel
undirected: true
configs:
  - [['gin', 32], ['relu'], ['gin', 64], ['relu'], ['gin', 128]]