# config.yaml
model: MRNet
type: 0
data_dir: data/ModelNet10
output: output/RNG_Modelnet10
epochs: 300
batch: 256
lr: 0.001
min_lr: 0.0000001
dropout: 0.5
keys: pos
graph_type: rng
undirected: true
configs:
  - [['mr', 'max', 32], ['relu'], ['mr', 'max', 32], ['relu'], ['mr', 'max', 128]]