# config.yaml
model: GINNet
type: 0
data_dir: data/SHAPENET_SKEL
output: output/Gabriel_Modelnet40
epochs: 300
batch: 64
lr: 0.001
min_lr: 0.0000001
dropout: 0.5
keys: 1
graph_type: gabriel
undirected: true
configs:
  - [['gin', 32], ['relu'], ['gin', 64], ['relu'], ['gin', 128]]